lib: [
  "_build/install/default/lib/http2/META" {"META"}
  "_build/install/default/lib/http2/opam" {"opam"}
  "_build/install/default/lib/http2/http2.cmi" {"http2.cmi"}
  "_build/install/default/lib/http2/http2.cmx" {"http2.cmx"}
  "_build/install/default/lib/http2/http2.cmt" {"http2.cmt"}
  "_build/install/default/lib/http2/http2.ml-gen" {"http2.ml-gen"}
  "_build/install/default/lib/http2/http2__Parse.cmi" {"http2__Parse.cmi"}
  "_build/install/default/lib/http2/http2__Parse.cmx" {"http2__Parse.cmx"}
  "_build/install/default/lib/http2/http2__Parse.cmt" {"http2__Parse.cmt"}
  "_build/install/default/lib/http2/parse.ml" {"parse.ml"}
  "_build/install/default/lib/http2/http2__Serialize.cmi" {"http2__Serialize.cmi"}
  "_build/install/default/lib/http2/http2__Serialize.cmx" {"http2__Serialize.cmx"}
  "_build/install/default/lib/http2/http2__Serialize.cmt" {"http2__Serialize.cmt"}
  "_build/install/default/lib/http2/serialize.ml" {"serialize.ml"}
  "_build/install/default/lib/http2/http2__Types.cmi" {"http2__Types.cmi"}
  "_build/install/default/lib/http2/http2__Types.cmx" {"http2__Types.cmx"}
  "_build/install/default/lib/http2/http2__Types.cmt" {"http2__Types.cmt"}
  "_build/install/default/lib/http2/http2__Types.cmti" {"http2__Types.cmti"}
  "_build/install/default/lib/http2/types.mli" {"types.mli"}
  "_build/install/default/lib/http2/types.ml" {"types.ml"}
  "_build/install/default/lib/http2/http2.cma" {"http2.cma"}
  "_build/install/default/lib/http2/http2.cmxa" {"http2.cmxa"}
  "_build/install/default/lib/http2/http2.a" {"http2.a"}
  "_build/install/default/lib/http2/http2.cmxs" {"http2.cmxs"}
  "_build/install/default/lib/http2/http2.dune" {"http2.dune"}
]
doc: [
  "_build/install/default/doc/http2/README.md"
]
